export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const FETCH_CLIENTS_ERROR = "FETCH_CLIENTS_ERROR";
export const SELECT_CLIENT = "SELECT_CLIENT";
export const SEARCH_TRIGGERED = "SEARCH_TRIGGERED";
export const SEARCH_TERM_UPDATED = "SEARCH_TERM_UPDATED";
