export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const FETCH_CLIENTS_ERROR = "FETCH_CLIENTS_ERROR";
export const SELECT_CLIENT = "SELECT_CLIENT";
export const SERCH_TRIGGERED = "SERCH_TRIGGERED";
